name: Update Octaspace Price
on: schedule
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          curl -s "https://api.coingecko.com/api/v3/simple/price?ids=octaspace&vs_currencies=usd" |
          jq -r '.octaspace.usd' > price.txt
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update Octaspace price"
          file_pattern: price.txt
